version: '3.1'

services:

  authentication:
    container_name: "authentication"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - eureka_default

  mongodb:
    container_name: "mongodb"
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: user
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - eureka_default

networks:
  eureka_default:
    external: true
